#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# #
#   @project        Backage
#   @usage          Endpoint behind badges for GitHub Packages
#   @repo           https://github.com/ipitio/backage
# #
